# Numpy

### array module

In [11]:
from array import array
my_array = array('i', [1,2,3,4,5])
my_array

array('i', [1, 2, 3, 4, 5])

### import numpy 

In [9]:
import numpy as np

In [13]:
arr = np.array([1,2,3,4])

In [15]:
arr

array([1, 2, 3, 4])

In [17]:
type(arr)

numpy.ndarray

In [19]:
arr.ndim

1

In [21]:
arr.dtype

dtype('int32')

In [23]:
import numpy as np

In [25]:
array_new = np.array([1,2,3,4,5,6])

In [27]:
array_new + 3

array([4, 5, 6, 7, 8, 9])

In [29]:
type(array_new)

numpy.ndarray

In [31]:
import numpy as np
my_numpy_array = np.array([1,2,3,4,5,6])

### using Numpy Arrays 




In [36]:
import numpy as np
my_array = np.array ([1,2,3])
result = my_array * 2
print(result)

[2 4 6]


In [38]:
import numpy as np
my_numpy_array = np.array ([1,2,3,4,5])

In [40]:
my_numpy_array * 3

array([ 3,  6,  9, 12, 15])

In [42]:
type(my_numpy_array)

numpy.ndarray

In [ ]:
#list vs numpy array

In [46]:
l = [1,2,3,45]

In [48]:
l*3

[1, 2, 3, 45, 1, 2, 3, 45, 1, 2, 3, 45]

In [50]:
array_new

array([1, 2, 3, 4, 5, 6])

In [52]:
array_new*2

array([ 2,  4,  6,  8, 10, 12])

In [54]:
my_array = np.array ([1,2,3])
result = my_array * 2
print(result)

[2 4 6]


In [56]:
arr

array([1, 2, 3, 4])

In [58]:
arr>2

array([False, False,  True,  True])

In [60]:
import seaborn as sns

In [62]:
df = sns.load_dataset("titanic")

In [64]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [66]:
df.shape

(891, 15)

In [68]:
l = [1,2,3]

In [70]:
l*2

[1, 2, 3, 1, 2, 3]

In [72]:
l = [[1,2,3],[1,2,3,4]]

In [74]:
l= [[1,2,3,4,5],
    [5,4,6,8,9],
    [4,5,8,9,10]]

In [76]:
array_2d = np.array([[1,2,3],[4,5,6]])

In [78]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
array_2d+2

array([[3, 4, 5],
       [6, 7, 8]])

In [82]:
matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

In [87]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


import pandas as pd

data = pd.read_csv('tit.csv')

print(data.head())

value = data.loc[0, 'column_name']
print(value)

In [95]:
data = pd.read_csv('tit.csv')

In [97]:
data

Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   
3             3         1       1  female  35.0      1      0  53.1000   
4             4         0       3    male  35.0      0      0   8.0500   
..          ...       ...     ...     ...   ...    ...    ...      ...   
886         886         0       2    male  27.0      0      0  13.0000   
887         887         1       1  female  19.0      0      0  30.0000   
888         888         0       3  female   NaN      1      2  23.4500   
889         889         1       1    male  26.0      0      0  30.0000   
890         890         0       3    male  32.0      0      0   7.7500   

    embarked   class    who  adult_male deck  embark_town alive  alone  
0          S   Third    man        True  NaN  Southampton    no  False  
1          C   First  woman       False    C    Cherbourg   yes  False  
2          S   Third  woman       False  NaN  Southampton   yes   True  
3          S   First  woman       False    C  Southampton   yes  False  
4          S   Third    man        True  NaN  Southampton    no   True  
..       ...     ...    ...         ...  ...          ...   ...    ...  
886        S  Second    man        True  NaN  Southampton    no   True  
887        S   First  woman       False    B  Southampton   yes   True  
888        S   Third  woman       False  NaN  Southampton    no  False  
889        C   First    man        True    C    Cherbourg   yes   True  
890        Q   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 16 columns]

In [99]:
import numpy as np 

list_data = [1,2,3,4,5]
array_from_list = np.array(list_data)

In [101]:
lis1 = [1,2,3,4,5]

In [103]:
lis1


[1, 2, 3, 4, 5]

In [105]:
lis1+10

TypeError: can only concatenate list (not "int") to list

In [107]:
type(lis1)

list

In [111]:
list_data = [1,2,3,4,5]
array_from_list = np.array(list_data)

In [113]:
list_data

[1, 2, 3, 4, 5]

In [115]:
type(list_data)

list

In [117]:
array_from_list

array([1, 2, 3, 4, 5])

In [119]:
type(array_from_list)

numpy.ndarray