# Array

In [3]:
import numpy as np

In [5]:
zeros_array = np.zeros((3,3))

In [ ]:
ones_array = np.ones((2,4))

In [ ]:
#using function to generate data 

In [102]:
a33 = np.ones((3,4))

In [104]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
type(a33)

numpy.ndarray

In [47]:
a44 =  np.zeros((2,4))

In [49]:
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
type(a44)

numpy.ndarray

In [13]:
l = [1,2,3,4]

In [15]:
np.array(l,dtype=np.int32)

array([1, 2, 3, 4])

In [21]:
import numpy as np
int_array= np.array([1,2,3], dtype=np.int32)
float_array = np.array([0.1,0.2,0.3], dtype=np.float64)

In [9]:
import numpy as np
linespace_array_2 = np.linspace(0,10,6)
linespace_array_2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [29]:
zerros_array = np.zeros((3,3))
ones_array = np.ones((2,4))
identity_matrix = np.eye(3)

In [43]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
random_array = np.random.rand(4,4)

In [33]:
random_array

array([[0.22955152, 0.85447737, 0.51859598, 0.75605154],
       [0.09073022, 0.71426958, 0.21130957, 0.14440178],
       [0.88393496, 0.44118613, 0.94601198, 0.36131809],
       [0.14922505, 0.92919364, 0.2349324 , 0.25242983]])

In [37]:
zerros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## NumPy array indexing 

### Basic Indexing

In [70]:


arr = np.array ([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


### 2D Example

In [73]:


matrix = np.array([[1,2,3],
                  [4,5,6]])
print(matrix[0,1])
print(matrix[1,2])

2
6


### 1D Array Slicing

In [76]:


arr = np.array([10,20,30,40,50])

print(arr[1:4])
print(arr[:3])
print(arr[::2])
print(arr[::-1])


[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [56]:
arr = np.array([10,20,30,40,50])

In [58]:
print(arr[1:4])

[20 30 40]


In [60]:
print(arr[:3])


[10 20 30]


In [62]:
print(arr[::2])

[10 30 50]


In [64]:
print(arr[::-1])

[50 40 30 20 10]


### 2D Array Slicing 

In [81]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix[0:2, 1:3])

#Slicing returns a view(not a copy), unless explicitly copied 

[[2 3]
 [5 6]]


In [93]:
print(matrix[1:2, 1:3])

[[5 6]]


In [106]:
print(matrix[2:3, 1:2])

[[8]]


In [ ]:
print(matrix[1:3, 1:

### copy vs view

In [112]:
a = np.array([1,2,3,4])


In [114]:
b = a[1:3] #view 

In [118]:
b[0]=99

In [120]:
print(a)

[ 1 99  3  4]


In [122]:

a = np.array([1,2,3,4])

In [126]:
b = a[1:3].copy()

In [128]:
b[0]=99

In [130]:
print(a)

[1 2 3 4]


In [132]:
print(b)

[99  3]


In [ ]:
use copy() when u want to modify data without affecting the original

### NumPy Shape

In [137]:
# shape tells dimention of array 

arr= np.array([[1,2,3], [4,5,6]])
print(arr.shape)

(2, 3)


### Reshaping Arrays

In [140]:
a = np.arange(12)
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [142]:
a = np.arange(12)

In [144]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [148]:
b= a.reshape(3,4)

In [150]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### transpose

In [153]:
arr_3d = np.array([[0,1,2,3],
                  [4,5,6,7],
                  [8,9,10,11]])

In [155]:
arr_3d.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])