In [1]:
import numpy as np

In [3]:
#uniform distribution
uniform = np.random.rand(3,3)
print(" Uniform distribution \n ", uniform)

 Uniform distribution 
  [[0.87139383 0.38876674 0.56023299]
 [0.26062167 0.72009309 0.22413388]
 [0.93770571 0.60265386 0.45818139]]


In [7]:
#searching in arrays 

arr = np.array([1,2,3,4,5])
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [9]:
np.where(arr<2)

(array([0], dtype=int64),)

In [11]:
print("where > 3:", np.where(arr>3))


where > 3: (array([3, 4], dtype=int64),)


### np.argmax() / np.argmin()

In [17]:
arr = np.array([1,2,3,4,5])

In [19]:
np.argmax(arr)

4

In [21]:
np.argmin(arr)

0

### np.searchsorted()

In [30]:
sorted_arr = np.array([1,3,5, 7])

In [32]:
np.searchsorted(sorted_arr,6)

3

In [34]:
np.searchsorted(sorted_arr,100)

4

In [38]:
print("Insert 6 at index ", np.searchsorted(sorted_arr,6))

Insert 6 at index  3


### np.extact()

In [41]:
arr = np.array([1,2,3,4,5])

In [47]:
np.extract(arr>3, arr)

array([4, 5])

In [49]:
print("extact > 3:", np.extract(arr>3, arr))

extact > 3: [4 5]


### transposing array

In [54]:
matrix = np.array([[1,2,3],
                  [4,5,6]])

In [56]:
# same as yesterday class 



print (" Transposed ", np.transpose(matrix))



 Transposed  [[1 4]
 [2 5]
 [3 6]]


### mean calculation 

In [59]:
arr = np.array([1,2,3,4,5])

In [61]:
print(" mean value :", np.mean(arr))

 mean value : 3.0


In [63]:
np.mean(arr)

3.0

### splitting arrays

In [66]:
#equal part split 
arr = np.array([1,2,3,4,5,6])

np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [70]:
#split specific positions
print ("split at indies :", np.split(arr, [2,3]))

split at indies : [array([1, 2]), array([3]), array([4, 5, 6])]


In [74]:
#split matrix,3,axis=1

np.split(matrix, 3, axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [76]:
#split matrix,2,axis=0

np.split(matrix, 2, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

### sorting arrays

In [79]:
arr = np.array([3,5,1,4,2])

In [81]:
np.sort(arr)

array([1, 2, 3, 4, 5])

In [83]:
arr.sort()

In [85]:
arr

array([1, 2, 3, 4, 5])

In [97]:
np.sort(matrix,axis=1) #rows

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.sort(matrix,axis=0) #coloum

array([[1, 2, 3],
       [4, 5, 6]])